In [5]:
from sklearn.linear_model import LinearRegression
import numpy as np
 
# 데이터 준비
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 3, 4,5])
# 모델 학습
model = LinearRegression()
model.fit(X, y)

# 기울기(회귀계수)와 절편 구하기
slope = model.coef_[0]
intercept = model.intercept_

print(f"기울기 (slope): {slope}")
print(f"절편 (intercept): {intercept}")

# 예측
X2 = np.array([[5], [6], [7], [8]])
y_pred = model.predict(X2)
print(y_pred)

기울기 (slope): 1.0
절편 (intercept): 1.0
[6. 7. 8. 9.]


In [11]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import numpy as np
 
X = np.array([[1], [2], [3], [4]]) # 데이터 준비
X2 = np.array([[1.1],[2.1],[3.1],[4.1]]) # 데이터 준비


y = np.array([1, 4, 9, 16])
poly = PolynomialFeatures(degree=2) # 다항 특징 생성
X_poly = poly.fit_transform(X)
model = LinearRegression() # 모델 학습
model.fit(X_poly, y)

poly2 = PolynomialFeatures(degree=2) # 다항 특징 생성
X_poly2 = poly2.fit_transform(X2)


y_pred = model.predict(X_poly) # 예측
print(y_pred)

y_pred2 = model.predict(X_poly2) # 예측
print(y_pred2)

# 다항식의 계수와 절편 출력
coef = model.coef_  # 다항식의 계수
intercept = model.intercept_  # 절편

print(f"다항식 계수 (기울기): {coef}")
print(f"다항식 절편: {intercept}")

[ 1.  4.  9. 16.]
[ 1.21  4.41  9.61 16.81]
다항식 계수 (기울기): [0.00000000e+00 2.10942375e-15 1.00000000e+00]
다항식 절편: 0.0
